name: z_emp
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.2.0+3

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Firebase Core for initializing Firebase
  firebase_core: ^3.6.0  # Latest stable version

  # Firestore for database operations
  cloud_firestore: ^5.4.4  # Latest stable version

  # Firebase Authentication for user authentication
  firebase_auth: ^5.3.1  # Latest stable version

  # Firebase Functions to call backend Cloud Functions (for payments)
  cloud_functions: ^5.1.5  # Latest stable version

  # Firebase Messaging for push notifications
  firebase_messaging: ^15.1.3  # Upgraded to avoid version conflicts

  # HTTP package to make API calls (e.g., ChatGPT integration)
  http: ^1.0.0

  # Provider for state management
  provider: ^6.1.2  # Latest stable version

  # Stripe or Razorpay can be used for payments (choose based on your gateway)
  # stripe_payment: ^1.0.9 # If you are using Stripe
  # razorpay_flutter: ^1.3.8 # If you are using Razorpay (uncomment if using)

  # For handling animations or advanced UI features
  flutter_animated_dialog: ^2.0.0

  # Use URL launcher if external links are opened within the app
  url_launcher: ^6.3.1

  # Use logger package for logging (correct version)
  logger: ^2.4.0

  # Firebase Storage for storing media files
  firebase_storage: ^12.3.4  # Latest stable version
  fl_chart: ^0.69.2
  intl: ^0.19.0
  file_picker: ^8.1.4
  image_picker: ^1.1.2
  flutter_typeahead: ^5.2.0
  salomon_bottom_bar: ^3.3.2
  font_awesome_flutter: ^10.8.0
  geolocator: ^13.0.2
  google_maps_flutter: ^2.10.0
  permission_handler: ^11.3.1
  table_calendar: ^3.1.2
  cached_network_image: ^3.4.1
  flutter_local_notifications: ^18.0.1
  firebase_app_check: ^0.3.1+6
  month_year_picker: ^0.4.0+1
  path: ^1.9.0
  timelines: ^0.1.0
  flutter_cupertino_date_picker_fork: ^1.0.7
  syncfusion_flutter_charts: ^27.2.4
  google_fonts: ^6.2.1
  flutter_launcher_icons: ^0.14.1
  infinite_scroll_pagination: ^4.1.0
  uuid: ^4.5.1
  record: ^5.2.0
  audioplayers: ^6.1.1
  flutter_sound: ^9.20.5
  cupertino_icons: ^1.0.8
  csv: ^6.0.0
  printing: ^5.14.0
  pdf: ^3.11.2
  share_plus: ^10.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Linter for ensuring code style and practices
  flutter_lints: ^5.0.0

flutter:

  # Assets (e.g., images, fonts)
  assets:
    - assets/images/
    - assets/fonts/
    - assets/images/default_profile.png
    - assets/images/preset_profiles/profile1.png
    - assets/images/preset_profiles/profile2.png
    - assets/images/preset_profiles/profile3.png
    - assets/images/logo.png
    - assets/images/login_bottom.png
    - assets/logo.png
    - assets/background.png
    

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700

  uses-material-design: true
  
flutter_launcher_icons:
  android: true 
  ios: true
  image_path: "assets/icons/app_icon.png" # Path to your icon image
  # For adaptive icons on Android (optional)
  #android_adaptive_icon:
  #foreground_image: "assets/icons/ic_foreground.png"
  #background_image: "assets/icons/ic_background.png"
  # If using SVGs, you need to provide PNGs instead as the package does not support SVG
