// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhdmxwTmdL2dyYqmyFWvVFP3Y21YDfpM4',
    appId: '1:68629169676:web:a60909852093dadd0fd029',
    messagingSenderId: '68629169676',
    projectId: 'z-emp-887',
    authDomain: 'z-emp-887.firebaseapp.com',
    storageBucket: 'z-emp-887.firebasestorage.app',
    measurementId: 'G-X9NK8FMS7H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0OzxISkI8bjJcAfiehAnwIwJd8snhsxE',
    appId: '1:68629169676:android:0556abf7e6dfc9910fd029',
    messagingSenderId: '68629169676',
    projectId: 'z-emp-887',
    storageBucket: 'z-emp-887.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfgLOj6k85-QFzzx4ZCcxPkSrSO2oJeuM',
    appId: '1:68629169676:ios:c25dcf2bec3139ac0fd029',
    messagingSenderId: '68629169676',
    projectId: 'z-emp-887',
    storageBucket: 'z-emp-887.firebasestorage.app',
    iosBundleId: 'com.example.zEmp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfgLOj6k85-QFzzx4ZCcxPkSrSO2oJeuM',
    appId: '1:68629169676:ios:c25dcf2bec3139ac0fd029',
    messagingSenderId: '68629169676',
    projectId: 'z-emp-887',
    storageBucket: 'z-emp-887.firebasestorage.app',
    iosBundleId: 'com.example.zEmp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDhdmxwTmdL2dyYqmyFWvVFP3Y21YDfpM4',
    appId: '1:68629169676:web:a2abdf278e84313b0fd029',
    messagingSenderId: '68629169676',
    projectId: 'z-emp-887',
    authDomain: 'z-emp-887.firebaseapp.com',
    storageBucket: 'z-emp-887.firebasestorage.app',
    measurementId: 'G-8VHH7EGK10',
  );

}